language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t helenosheaa/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true helenosheaa/react-test npm test

after_success:
  - docker build -t helenosheaa/multi-client ./client 
  - docker build -t helenosheaa/multi-nginx ./nginx 
  - docker build -t helenosheaa/multi-server ./server 
  - docker build -t helenosheaa/multi-worker ./worker 

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin docker.io

  - docker push helenosheaa/multi-client
  - docker push helenosheaa/multi-nginx
  - docker push helenosheaa/multi-server
  - docker push helenosheaa/multi-worker

deploy: 
  edge: true
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-2-722207080935"
  bucket_path: "multi-docker"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY